# Generated by Django 4.2 on 2024-12-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vendor',
            new_name='vendors',
        ),
    ]
