# Generated by Django 4.2 on 2024-11-21 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(50, 'Review must be at least 50 characters long.')]),
        ),
    ]
